# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
