# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.IntegerField(),
        ),
    ]
